name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: ðŸŽ‰ iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # Get Flutter packages
      - run: flutter pub get

      # Ensure iOS folder exists
      - run: flutter create --platforms=ios .

      # Clean old pods/cache
      - run: |
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          flutter clean
          flutter pub get

      # Set minimum iOS deployment target to 14
      - name: Set iOS deployment target to 14
        run: |
          # Ensure platform is 14
          sed -i '' "s/platform :ios, .*/platform :ios, '14.0'/g" ios/Podfile || echo "platform :ios, '14.0'" >> ios/Podfile

          # Inject deployment target into existing post_install
          perl -0777 -i -pe "s/(post_install do \|installer\|.*?end)/\$1\ninstaller.pods_project.targets.each { |t| t.build_configurations.each { |c| c.build_settings['IPHONEOS_DEPLOYMENT_TARGET']='14.0' } }/s" ios/Podfile

      # Update CocoaPods repo and install
      - run: pod repo update
        working-directory: ios

      - run: pod install
        working-directory: ios

      # Build iOS release
      - run: flutter build ios --release --no-codesign

      # Package IPA
      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      # Upload IPA to GitHub Release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
